### ISSUE TITLE
Why does `PostsList.svelte` already contain content?

### ISSUE THREAD

**Issue by bartvdbraak** [subhendupsingh/sveltekit-notion-blog#2]
Is the purpose for these components to be reusable by others?

I think it's strange when I tried to use it, it had already the following content:

```
<div class="flex flex-col gap-12 mb-8">
    <h1 class="font-bold text-4xl">Welcome to StoreBud blog - Platform for growing D2C brands!</h1>

    <p class="text-lg">
        StoreBud blogs cover variuos topics related to setting up your own ecommerce website in India and 
        other parts of the world, including tips and tricks, best practices and success stroies of the 
        growing D2C brands.
    </p>
</div>
```

**Comment by subhendupsingh** [comment]
Yes, that's me being naive. This is my first open-source lib. Fixed this with 

https://github.com/subhendupsingh/sveltekit-notion-blog/commit/e48263c1bda59309be634a105b73150b7d255adf

**Comment by bartvdbraak** [comment]
No problems! I learn a lot from your project :)

**Comment by subhendupsingh** [comment]
Let me know if you are using it, would love to know what more features you would want me to add.

**Comment by subhendupsingh** [comment]
Fixed
https://github.com/subhendupsingh/sveltekit-notion-blog/commit/e48263c1bda59309be634a105b73150b7d255adf
